# fly.toml app configuration file generated for nick-preston-portfolio on 2023-10-24T18:05:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nick-preston-portfolio"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
